"""
`tools/ca_orders.py` — the driver that turns HAA_G12's decision into Canadian orders.

Everything here is offline. The driver's three fetchers (signal, quotes, FX) are arguments of
`main`, and the tests that exercise the refusal paths pass fetchers that RAISE: a refusal that
happened after a download would pass a test that merely checked the exit code, and would
still have spent a network round-trip on a config it was always going to reject.

Anchors, in the sense of `tests/test_anchors.py`:

* the Yahoo symbols are the ones probed against Yahoo on 2026-09-23, written as literals —
  including the fact that the three Cboe Canada funds answer only as `.NE`;
* the demonstration CSV is compared byte for byte with the committed file, which was produced
  once and reviewed, not regenerated by the test;
* the demonstration's own inputs are recorded public prices and rates, and its capital is
  fictional and says so.
"""
import datetime
import io
import json
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from unittest import mock

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import pandas as pd

from common import ca_mapping as cam
from common.ca_execution import CAExecutionError, FxRate
from tools import ca_orders as co

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
RATE = FxRate(usdcad=1.40, source='test', as_of='2026-09-22')


def _boom(*_a, **_k):
    raise AssertionError('a fetcher was called; this path must refuse before any network')


def _config(**over):
    raw = {'cash': {'CAD': 100_000.0, 'USD': 0.0}, 'positions': [],
           'execution': {'prefer_usd_units': False}}
    raw.update(over)
    return raw


def _write(tmp, raw):
    path = os.path.join(tmp, 'ca_execution.json')
    with open(path, 'w', encoding='utf-8') as fh:
        json.dump(raw, fh)
    return path


def _quiet(fn, *a, **k):
    buf = io.StringIO()
    with redirect_stdout(buf):
        rc = fn(*a, **k)
    return rc, buf.getvalue()


class TestTheConfigIsStrict(unittest.TestCase):

    def test_a_missing_file_points_at_the_template(self):
        with self.assertRaises(co.ConfigError) as ctx:
            co.load_config(os.path.join(ROOT, 'no-such-dir', 'ca_execution.json'))
        self.assertIn('ca_execution.example.json', str(ctx.exception))
        self.assertIn('gitignored', str(ctx.exception))

    def test_the_committed_template_parses(self):
        cfg = co.load_config(co.EXAMPLE_PATH)
        self.assertEqual(cfg['exec_config'].leverage, 1.0)
        cam.assert_no_us_tickers([p['ticker'] for p in cfg['positions']])

    def test_a_misspelt_key_is_refused_rather_than_ignored(self):
        """`positons` ignored would be a book with no holdings, bought a second time."""
        with self.assertRaises(co.ConfigError) as ctx:
            co.parse_config(_config(positons=[{'ticker': 'ZSP', 'qty': 1}]))
        self.assertIn('positons', str(ctx.exception))

    def test_a_us_ticker_among_the_holdings_is_refused(self):
        with self.assertRaises(ValueError) as ctx:
            co.parse_config(_config(positions=[{'ticker': 'SPY', 'qty': 10}]))
        self.assertIn('SPY', str(ctx.exception))

    def test_a_stated_currency_must_match_the_table(self):
        with self.assertRaises(co.ConfigError):
            co.parse_config(_config(positions=[{'ticker': 'ZSP.U', 'qty': 10,
                                                'currency': 'CAD'}]))

    def test_the_currency_is_read_off_the_table_when_not_stated(self):
        cfg = co.parse_config(_config(positions=[{'ticker': 'UBIL.U', 'qty': 3}]))
        self.assertEqual(cfg['positions'][0]['currency'], 'USD')

    def test_negative_cash_and_non_numbers_are_refused(self):
        for raw in (_config(cash={'CAD': -1.0}), _config(cash={'CAD': True}),
                    _config(cash={'EUR': 1.0}),
                    _config(positions=[{'ticker': 'ZSP', 'qty': 0}]),
                    _config(positions=[{'ticker': 'ZSP', 'qty': 'ten'}])):
            with self.subTest(raw=raw), self.assertRaises(co.ConfigError):
                co.parse_config(raw)

    def test_leverage_above_one_is_refused(self):
        with self.assertRaises(CAExecutionError) as ctx:
            co.parse_config(_config(execution={'leverage': 1.3}))
        self.assertIn('EXEC-001', str(ctx.exception))

    def test_an_unknown_execution_setting_is_refused(self):
        with self.assertRaises(co.ConfigError):
            co.parse_config(_config(execution={'leverage_factor': 1.0}))


class TestYahooSymbols(unittest.TestCase):
    """Probed against Yahoo on 2026-09-23, every one of the twenty."""

    def test_the_probed_symbols(self):
        self.assertEqual(co.yahoo_symbol('ZSP'), 'ZSP.TO')
        self.assertEqual(co.yahoo_symbol('ZSP.U'), 'ZSP-U.TO')
        self.assertEqual(co.yahoo_symbol('CGL.C'), 'CGL-C.TO')
        self.assertEqual(co.yahoo_symbol('UBIL.U'), 'UBIL-U.TO')
        self.assertEqual(co.yahoo_symbol('ZTL'), 'ZTL.NE')
        self.assertEqual(co.yahoo_symbol('ZTM.U'), 'ZTM-U.NE')

    def test_exactly_the_cboe_canada_funds_are_quoted_as_ne(self):
        ne = sorted(t for t in cam.all_execution_tickers()
                    if co.yahoo_symbol(t).endswith('.NE'))
        self.assertEqual(ne, ['ZCOM', 'ZTL', 'ZTL.U', 'ZTM', 'ZTM.U'])

    def test_a_ticker_outside_the_table_has_no_symbol(self):
        with self.assertRaises(co.ConfigError):
            co.yahoo_symbol('SPY')


def _frame(closes):
    """A yfinance-shaped frame: columns ('Close', symbol)."""
    df = pd.DataFrame(closes)
    df.index = pd.to_datetime(df.index)
    df.columns = pd.MultiIndex.from_product([['Close'], df.columns])
    return df


class TestQuotesAreCheckedNotTrusted(unittest.TestCase):

    def test_the_last_close_on_or_before_the_date_is_taken(self):
        frame = _frame({'ZSP.TO': {'2026-09-18': 118.0, '2026-09-21': 119.0,
                                   '2026-09-23': 999.0},
                        'CGL-C.TO': {'2026-09-18': 50.0, '2026-09-21': float('nan'),
                                     '2026-09-23': float('nan')}})
        quotes = co.fetch_quotes({'ZSP', 'CGL.C'}, '2026-09-22',
                                 download=lambda *a, **k: frame)
        self.assertEqual(quotes['ZSP'], (119.0, '2026-09-21'))
        self.assertEqual(quotes['CGL.C'], (50.0, '2026-09-18'))

    def test_a_symbol_yahoo_did_not_return_is_absent_not_zero(self):
        frame = _frame({'ZSP.TO': {'2026-09-21': 119.0}})
        quotes = co.fetch_quotes({'ZSP', 'ZCOM'}, '2026-09-22',
                                 download=lambda *a, **k: frame)
        self.assertNotIn('ZCOM', quotes)

    def test_a_missing_or_stale_required_quote_is_a_refusal(self):
        quotes = {'ZSP': (119.0, '2026-09-01')}
        _, problems, _ = co.check_quotes({'ZSP', 'CGL.C'}, set(), quotes, '2026-09-22')
        self.assertEqual(len(problems), 2)
        self.assertTrue(any('ZSP' in p and '21 days' in p for p in problems))
        self.assertTrue(any('CGL.C' in p and 'no quote' in p for p in problems))

    def test_a_missing_alternative_class_is_only_a_note(self):
        prices, problems, notes = co.check_quotes({'ZSP'}, {'ZSP.U'},
                                                  {'ZSP': (119.0, '2026-09-22')}, '2026-09-22')
        self.assertEqual(problems, [])
        self.assertEqual(prices, {'ZSP': 119.0})
        self.assertTrue(any('ZSP.U' in n for n in notes))

    def test_required_and_optional_tickers(self):
        req, opt = co.quote_tickers({'SPY': 1.0}, [])
        self.assertEqual((req, opt), ({'ZSP'}, {'ZSP.U'}))
        req, opt = co.quote_tickers({'BIL': 1.0},
                                    [{'ticker': 'ZSP', 'qty': 5, 'currency': 'CAD'}])
        self.assertEqual((req, opt), ({'UBIL.U', 'ZSP'}, set()))


SIGNAL = co.Signal({'SPY': 0.5, 'GLD': 0.5}, '2026-08-31', {'TIP': 0.01}, None,
                   {'source': 'test'})
#: Dated today, not on a fixed day: `main` judges a quote's age against the real clock, so a
#: fixed date turned these driver tests red twelve days after they were written.
TODAY = datetime.date.today().isoformat()
FRESH = {'ZSP': (100.0, TODAY), 'ZSP.U': (100.0 / 1.4, TODAY), 'CGL.C': (50.0, TODAY)}


class TestTheDriver(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)

    def _main(self, raw, *argv, signal=SIGNAL, quotes=FRESH):
        path = _write(self.tmp.name, raw)
        return _quiet(co.main, ['--config', path, '--no-journal', *argv],
                      fetch_signal=lambda: signal,
                      fetch_quotes_fn=lambda tickers, day: dict(quotes),
                      fx_resolver=lambda manual=None: RATE)

    def test_a_missing_config_refuses_before_any_fetch(self):
        rc, out = _quiet(co.main, ['--config', os.path.join(self.tmp.name, 'none.json')],
                         fetch_signal=_boom, fetch_quotes_fn=_boom, fx_resolver=_boom)
        self.assertEqual(rc, 1)
        self.assertIn('does not exist', out)

    def test_refused_leverage_refuses_before_any_fetch(self):
        path = _write(self.tmp.name, _config(execution={'leverage': 1.3}))
        rc, out = _quiet(co.main, ['--config', path], fetch_signal=_boom,
                         fetch_quotes_fn=_boom, fx_resolver=_boom)
        self.assertEqual(rc, 1)
        self.assertIn('EXEC-001', out)

    def test_hand_computed_orders(self):
        """100,000 CAD, 50/50, at 100.00 and 50.00: 500 ZSP and 1,000 CGL.C."""
        rc, out = self._main(_config())
        self.assertEqual(rc, 0, out)
        self.assertRegex(out, r'BUY\s+500\s+ZSP\s')
        self.assertRegex(out, r'BUY\s+1,000\s+CGL\.C\s')
        # The weights line names SPY and GLD, as it should; no ORDER line may.
        traded = [line.split()[2] for line in out.splitlines()
                  if line.split()[:1] in (['BUY'], ['SELL'])]
        self.assertEqual(sorted(traded), ['CGL.C', 'ZSP'])
        cam.assert_no_us_tickers(traded)

    def test_a_stale_quote_refuses(self):
        stale = dict(FRESH, ZSP=(100.0, '2026-08-01'))
        rc, out = self._main(_config(), quotes=stale)
        self.assertEqual(rc, 1)
        self.assertIn('too old', out)

    def test_a_typed_price_wins_over_the_download(self):
        rc, out = self._main(_config(prices={'ZSP': 200.0}))
        self.assertEqual(rc, 0, out)
        self.assertRegex(out, r'BUY\s+250\s+ZSP\s')

    def test_a_stale_signal_is_printed_first(self):
        signal = SIGNAL._replace(stale_note='SIGNAL IS 2 MONTHS OLD')
        rc, out = self._main(_config(), signal=signal)
        self.assertEqual(rc, 0)
        self.assertLess(out.index('SIGNAL IS 2 MONTHS OLD'), out.index('BUY'))

    def test_the_journal_is_written_under_logs_and_every_row_names_its_signal(self):
        cfg = co.parse_config(_config())
        result = co.build(cfg, SIGNAL, {'ZSP': 100.0, 'CGL.C': 50.0}, RATE)
        jpath, cpath = co.journal(result, SIGNAL, FRESH, [], directory=self.tmp.name)
        with open(cpath, encoding='utf-8') as fh:
            rows = list(__import__('csv').DictReader(fh))
        self.assertTrue(rows)
        self.assertEqual({r['signal_date'] for r in rows}, {'2026-08-31'})
        with open(jpath, encoding='utf-8') as fh:
            self.assertEqual(json.load(fh)['signal']['signal_date'], '2026-08-31')

    def test_the_default_journal_and_config_are_outside_git(self):
        self.assertEqual(os.path.commonpath([co.JOURNAL_DIR, os.path.join(ROOT, 'logs')]),
                         os.path.join(ROOT, 'logs'))
        with open(os.path.join(ROOT, '.gitignore'), encoding='utf-8') as fh:
            ignored = {line.strip() for line in fh}
        self.assertIn('logs/', ignored)
        self.assertIn('ca_execution.json', ignored)
        self.assertNotIn('ca_execution.example.json', ignored)


class TestTheDemonstration(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.results, cls.csv_text = co.run_demo()
        with open(co.DEMO_INPUT, encoding='utf-8') as fh:
            cls.demo = json.load(fh)

    def test_it_reproduces_the_committed_csv_byte_for_byte(self):
        with open(co.DEMO_CSV, encoding='utf-8', newline='') as fh:
            self.assertEqual(self.csv_text, fh.read())

    def test_the_capital_is_declared_fictional(self):
        self.assertIn('FICTIONAL', self.demo['_comment'])
        self.assertEqual(self.demo['cash'], {'CAD': 100000.0, 'USD': 0.0})

    def test_every_row_names_one_of_the_demonstrated_signals(self):
        months = {m['signal_date'] for m in self.demo['months']}
        rows = list(__import__('csv').DictReader(io.StringIO(self.csv_text)))
        self.assertEqual({r['signal_date'] for r in rows}, months)

    def test_no_us_ticker_reaches_the_demonstration(self):
        rows = list(__import__('csv').DictReader(io.StringIO(self.csv_text)))
        traded = [r['exec_ticker'] for r in rows if r['side'] != 'CONVERT']
        cam.assert_no_us_tickers(traded)

    def test_the_second_month_is_a_full_rotation_into_the_defensive_sleeve(self):
        """August 2026: TIP's 13612U is negative, the canary is dead, HAA_G12 is 100% BIL —
        so every July holding is sold, CAD is converted, and UBIL.U is bought."""
        signal, result = self.results[1]
        self.assertLess(signal.canary['TIP'], 0)
        self.assertEqual(signal.weights, {'BIL': 1.0})
        sides = [(o['side'], o['ticker']) for o in result['orders']]
        self.assertEqual(sorted(t for s, t in sides if s == 'SELL'),
                         sorted(o['ticker'] for o in self.results[0][1]['orders']))
        self.assertEqual([t for s, t in sides if s == 'BUY'], ['UBIL.U'])
        self.assertEqual([f['direction'] for f in result['fx_orders']], ['CAD->USD'])


if __name__ == '__main__':
    unittest.main()
